service: yandex-cloud-nodejs
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16


plugins:
  - "@yandex-cloud/serverless-plugin"

package:
  individually: true

functions:
  get-state:
    handler: dist/server/get-state.handler
    memorySize: 512
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/get-state.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}

  get-config:
    handler: dist/server/get-config.handler
    memorySize: 128
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/get-config.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}

  move:
    handler: dist/server/move.handler
    memorySize: 512
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/move.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}
      YMQ_WRITER_ACCESS_KEY_ID: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_id}
      YMQ_WRITER_SECRET_ACCESS_KEY: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_secret}
      YMQ_CAPTURE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_capture_queue_url}
      YMQ_STATE_CHANGE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_state_change_queue_url}

  capture:
    handler: dist/server/capture.handler
    memorySize: 2048
    timeout: 5
    account: functions-sa
    events:
      - ymq:
          account: triggers-sa
          queueAccount: ymq-reader-sa
          queue: capturing-queue
          batch: 10
          cutoff: 1
    package:
      patterns:
        - '!**'
        - dist/server/capture.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}
      YMQ_WRITER_ACCESS_KEY_ID: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_id}
      YMQ_WRITER_SECRET_ACCESS_KEY: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_secret}
      YMQ_STATE_CHANGE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_state_change_queue_url}

  state-change:
    handler: dist/server/state-change.handler
    memorySize: 2048
    timeout: 5
    account: functions-sa
    events:
      - ymq:
          account: triggers-sa
          queueAccount: ymq-reader-sa
          queue: notify-state-change
          batch: 10
          cutoff: 1
    package:
      patterns:
        - '!**'
        - dist/server/state-change.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}

  login:
    handler: dist/server/login.handler
    memorySize: 128
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/login.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}
      TG_BOT_TOKEN: ${lockbox:${env:LOCKBOX_SECRET_ID}/tg_bot_token}
      YMQ_WRITER_ACCESS_KEY_ID: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_id}
      YMQ_WRITER_SECRET_ACCESS_KEY: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_secret}
      YMQ_STATE_CHANGE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_state_change_queue_url}


  auth:
    handler: dist/server/auth.handler
    memorySize: 128
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/auth.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}
      TG_BOT_TOKEN: ${lockbox:${env:LOCKBOX_SECRET_ID}/tg_bot_token}

  ws-connect:
    handler: dist/server/ws-connect.handler
    memorySize: 128
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/ws-connect.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}

  ws-message:
    handler: dist/server/ws-message.handler
    memorySize: 2048
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/ws-message.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}
      YMQ_WRITER_ACCESS_KEY_ID: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_id}
      YMQ_WRITER_SECRET_ACCESS_KEY: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_writer_key_secret}
      YMQ_CAPTURE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_capture_queue_url}
      YMQ_STATE_CHANGE_URL: ${lockbox:${env:LOCKBOX_SECRET_ID}/ymq_state_change_queue_url}

  ws-disconnect:
    handler: dist/server/ws-disconnect.handler
    memorySize: 128
    timeout: 5
    account: functions-sa
    package:
      patterns:
        - '!**'
        - dist/server/ws-disconnect.js
    environment:
      YDB_ENDPOINT: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_endpoint}
      YDB_DB: ${lockbox:${env:LOCKBOX_SECRET_ID}/ydb_db}


resources:
  functions-sa:
    type: yc::ServiceAccount
    roles:
      - editor
  triggers-sa:
    type: yc::ServiceAccount
    roles:
      - serverless.functions.invoker
  ymq-reader-sa:
    type: yc::ServiceAccount
    roles:
      - editor
  ymq-writer-sa:
    type: yc::ServiceAccount
    roles:
      - editor
  serverless-game-files:
    type: yc::ObjectStorageBucket
  capturing-queue:
    type: yc::MessageQueue
  notify-state-change:
    type: yc::MessageQueue

